networks:
  laravel_network:
    driver: bridge
services:
  app:
    build:
      context: ./docker/php
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    working_dir: /app
    command: php -S 0.0.0.0:80 -t /app/public
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/project
    networks:
      - laravel_network

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:
